name: manual-github-actions
on: workflow_dispatch
  inputs:
    logLevel:
      description: 'Log Levle'
      required: true
      default: 'warning'
    tags:
      description: 'Cloud Tags'
jobs:
  trigger-manual-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Trigger Manual Action
        run: uname -a
        run: date
    
    - run: |
        echo "Log level set to : ${{github.event.inputs.logLevel}}"
        echo "Log level set to : ${{github.event.inputs.tags}}"        